Adding cron for daily tests and builds on Mercodee
keep-network/sortition-pools pull request #119
Opened 2021-09-07 14:19 UTC by dimpar

The purpose of this PR is to set a cron job that would run tests and builds on a daily basis (at midnight) so the results can be displayed on Meercode dashboard.

2021-09-07 20:45 UTC, michalinacienciala requested changes
One small change suggested.

2021-09-07 20:45 UTC, michalinacienciala commented on .github/workflows/solidity-test.yml
> +      - cron: '0 0 * * *'
```suggestion
    - cron: '0 0 * * *'
```

2021-09-08 08:09 UTC, dimpar commented on .github/workflows/solidity-test.yml
> +      - cron: '0 0 * * *'
Done

2021-09-08 08:14 UTC, michalinacienciala approved these changes

2021-09-08 08:22 UTC, merged